const actionTypes = {
  // auth
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  GET_CURRENT: 'GET_CURRENT',

  //cart
  FETCH_CART: 'FETCH_CART',
};

export default actionTypes;
